import type { Metadata } from "next";
import { Khula, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";

const khula = Khula({
  variable: "--font-khula",
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${khula.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
